### ISSUE TITLE
Wide images in reviews can break layout

### ISSUE THREAD

**Issue by atdt** [eloquence/lib.reviews#71]
For example:

<img width="454" alt="sszxkzy" src="https://cloud.githubusercontent.com/assets/376462/19402751/d4a76a1e-9230-11e6-8962-6e41babffb91.png">

The following CSS rule should fix it:

```css
.review-text img {
  max-width: 100%;
}
```
